### ISSUE TITLE
Can't seem to get default colour to work

### ISSUE THREAD

**Issue by alancwoo** [hananils/kirby-colors#10]
Thanks for this wonderful plugin. For some reason I can't seem to get the default colours to work:

blueprint:
```
color_text:
    label: Text Color
    type: colors
    default: 'rgb(0, 0, 0)'
```

Results in a transparent picker with no default value set:
<img width="726" alt="image" src="https://user-images.githubusercontent.com/1481890/79361089-1fba5e80-7f45-11ea-9e8b-daebf614932f.png">

Am I setting it incorrectly?
