### ISSUE TITLE
Curious color behavior

### ISSUE THREAD

**Issue by N247S** [hananils/kirby-colors#12]
Blueprint setup
```yml
  header_background_color:
    label: Header color
    type: colors
    alpha: true
    width: 1/2
```

Php context
```php
# used this method to obtain the color-string
$site->header_background_color()->toColor();
```

input:
![image](https://user-images.githubusercontent.com/10078398/97054387-fda13900-1584-11eb-8644-6a19a1cebf81.png)

output:
![image](https://user-images.githubusercontent.com/10078398/97054604-5cff4900-1585-11eb-8f8e-d5db50cf8358.png)

If more information is required, let me know!
