### ISSUE TITLE
additional sources for contrast colors

### ISSUE THREAD

**Issue by bnomei** [hananils/kirby-colors#2]
to keep the color definitions DRY... being able to pull the colors from

- config setting
- another field using query language

would be awesome.

**Comment by nilshoerrmann** [comment]
That's a good idea, especially using the query language. But I have no idea how to do this actually.

**Comment by bnomei** [comment]
you could try to get inspiration from here:
https://github.com/sylvainjule/kirby-color-palette#dynamic-options

**Comment by distantnative** [comment]
If you have figured out a good syntax, it's not too difficult, @nilshoerrmann:

1. Create the prop in the PHP field setup. Can be very simple

```php
'yourProp' => function (string $prop = null) {
    return $prop;
},
```

2. Create a computed prop, that will take the normal prop and run it as a query:

```php
'yourProp' => function () {
    if ($this->yourProp !== null) {
        return $this->model()->toString($this->yourProp);
    }
},
```

**Comment by ebz8** [comment]
Hi, is there a way today to configure contrast options with a query  from an other field? (if I want to pick colors for background AND text in my panel and check accessibility) Thank you :)

**Comment by nilshoerrmann** [comment]
No, I don't think so. But we should finally add this option. Can you provide me with the desired field setup in YAML you were thinking of?

**Comment by ebz8** [comment]
It would be wonderfull!!
I tried something like that:

```yaml
fields:
  backgroundcolor:
    type: colors
    alpha: true
    default: "#ff"

  textcolor:
     type: colors
     alpha: true
     contrast:
       type: query
       query: page.backgroundcolor    // or   page.backgroundcolor.toStructure and a correct text/value like {{item.color}}
    default: "#00"

```

I don't know, something like kirby-color-palette dynamic option and queries for kirby 3.8.1 select fields ?

**Comment by nilshoerrmann** [comment]
So I noticed something that certainly is the reason why we have not implemented this yet: it's one thing to set up the relationship between two field via queries in the blueprint – that's purely on the server. But we also have to deal with live updates inside the panel, in the browser. E. g. your two fields are on the same page and thus changing the one should automatically update the other on the fly. So somehow the Vue components have to listen to other fields as well and not just the PHP backend.

Are there other examples of fields doing this already?

**Comment by Werbschaft** [comment]
We had Sylvain Jule make us a plugin that we can get colours directly from the site settings. It is still online and can be found here. It's in heavy use every day and with cache function.

https://github.com/sylvainjule/kirby-color-palette/tree/custom-classes

**Comment by nilshoerrmann** [comment]
Thanks @Werbschaft!

I'm thinking about a good syntax. So we have this pattern for server side rendered options already:

```yaml
contrast:
  type: query
  query: site.colors
```

What about this for live field updates?

```yaml
contrast:
  type: watch
  field: nameoffield
```

Alternatively (or additionally), it could also be an idea to add an option to edit the contrast color directly, allowing users to switch the color they are editing:

```yaml
contrast: editable
```

![grafik](https://user-images.githubusercontent.com/25466/200615100-dab9192f-3c59-4636-9d91-e107f53a7068.png)
