### ISSUE TITLE
$field->toMostReadable() not using contrast values from blueprint

### ISSUE THREAD

**Issue by FynnZW** [hananils/kirby-colors#25]
The contrast list from the blueprint is not being used.
The function always returns #000 or #FFF.

My blueprint:
```yaml
    backgroundcolor:
      type: colors
      contrast:
        - '#112233'
        - '#778899'
```
